size(200,200);
float y = 20; 
ellipse(7, y, width, y);
y = y * 2.6; 
ellipse(0, y, width, y);
y = y * 2.6;
ellipse(0, y, width, y);
y = y * 1.4;
ellipse(0, y, width, y);
y = y * 6.6;
ellipse(0, y, width, y);
y = y * 3.6; 
y = y * 1.6; 
ellipse(0, y, width, y);
